# Generated by Django 5.1.4 on 2025-06-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmith', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksdetail',
            name='maximum_completions',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
