# Generated by Django 5.1.4 on 2025-05-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmith', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
