# Generated by Django 5.1.4 on 2025-06-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmith', '0002_tasksdetail_maximum_completions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
