# Generated by Django 5.1.4 on 2025-06-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmith', '0003_alter_requirements_name_alter_tags_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksdetail',
            old_name='maximum_completions',
            new_name='task_maximum_completions',
        ),
        migrations.RenameField(
            model_name='tasksdetail',
            old_name='requirements',
            new_name='task_requirements',
        ),
        migrations.RenameField(
            model_name='tasksdetail',
            old_name='reward_per_completion',
            new_name='task_reward_per_completion',
        ),
        migrations.RenameField(
            model_name='tasksdetail',
            old_name='tags',
            new_name='task_tags',
        ),
        migrations.AddField(
            model_name='tasksdetail',
            name='task_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
