# Generated by Django 5.1.4 on 2025-05-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmith', '0003_alter_tasksdetail_task_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdetail',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
