# Generated by Django 5.1.4 on 2025-07-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmith', '0004_rename_maximum_completions_tasksdetail_task_maximum_completions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdetail',
            name='task_status',
            field=models.CharField(choices=[('pending', 'Prnding'), ('approved', 'Approved'), ('review', 'Review'), ('completed', 'Completed'), ('in_progress', 'InProgress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
    ]
