# Generated by Django 5.1.4 on 2025-05-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmith', '0004_alter_tasksdetail_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdetail',
            name='task_url',
            field=models.URLField(max_length=500),
        ),
    ]
