# Generated by Django 5.1.4 on 2025-07-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmith', '0005_alter_tasksdetail_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdetail',
            name='task_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('review', 'Review'), ('completed', 'Completed'), ('in_progress', 'InProgress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
    ]
