# Generated by Django 5.1.4 on 2025-05-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apple_auth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook_auth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_auth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_paid',
        ),
    ]
