# Generated by Django 5.1.4 on 2025-05-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tasksmith', 'Tasksmith'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
