# Generated by Django 5.1.4 on 2025-07-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='location',
        ),
    ]
