# Generated by Django 5.1.4 on 2025-07-02 13:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_image_alter_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
