# Generated by Django 5.1.4 on 2025-07-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'user_specialties',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='authentication.specialty'),
        ),
    ]
